default_language_version:
  python: "3.11"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.258"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
  - repo: https://github.com/python-formate/flake8-dunder-all
    rev: v0.2.2
    hooks:
      - id: ensure-dunder-all
        exclude: "test*|examples*|tools"
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.16.5
    hooks:
      - id: slotscheck
        exclude: "test_*|docs"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.1.1"
    hooks:
      - id: mypy
        additional_dependencies: [pydantic]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.300
    hooks:
      - id: pyright
        additional_dependencies: [pytest]
