name: Test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      coverage:
        required: false
        type: boolean
        default: false
      os:
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  test:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: ${{ inputs.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Test
        if: ${{ !inputs.coverage }}
        run: uv run pytest

      - name: Test with coverage
        if: inputs.coverage
        run: uv run pytest docs/examples tests --cov=project_template --cov-report=xml

      - uses: actions/upload-artifact@v7
        if: inputs.coverage
        with:
          name: coverage-xml
          path: coverage.xml
