name: Test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      coverage:
        required: false
        type: boolean
        default: false
      os:
        required: false
        type: string
        default: "ubuntu-latest"

permissions: {}

jobs:
  test:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: ${{ inputs.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Test
        if: ${{ !inputs.coverage }}
        run: uv run pytest

      - name: Test with coverage
        if: inputs.coverage
        run: uv run pytest docs/examples tests --cov=project_template --cov-report=xml

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: inputs.coverage
        with:
          name: coverage-xml
          path: coverage.xml
